version: '3.4'
services:
  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: elasticsearch
    ports:
    - 9200:9200
    - 9300:9300
    environment:
    - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    - discovery.type=single-node
    - xpack.security.enabled=false
    networks:
      - elastic

networks:
  elastic:
    driver: bridge